### ISSUE TITLE
Hi, when will conda link be released?

### ISSUE THREAD

**Issue by dlyldxwl** [IVRL/AI4VA#1]
~

**Comment by baharay** [comment]
Hi, we will release the codalab link in a few days. Meanwhile, you can start exploring the dataset and train your models on the given train-validation split.

**Comment by dlyldxwl** [comment]
Thank you for your reply.
Please note that Segmentation fold not has baseline_model.ipynb file. Is this an omission?

**Comment by deblinaml** [comment]
Hi, our apologies- the segmentation challenge is not available in this iteration of the workshop. We will make it available in a future iteration. However, the segmentation data annotations are still available for you to explore. Hint: These segments might be beneficial to the other two challenges. 
Best wishes!

**Comment by deblinaml** [comment]
Closing the issue since the thread is resolved. If there are any further questions, please feel free to reopen the issue.
