### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by Flrotm** [IVRL/AI4VA#3]
Hey, I can't find the "model/custom_dataset.py" in the salience challenge.

**Comment by baharay** [comment]
Hi,

It is a placeholder file to implement your dataloader and data transformations/augmentations. I have uploaded a [basic dataloader here](https://github.com/IVRL/AI4VA/blob/f147cbf1811b88179c6ef272bbfe076a5f206a01/saliency/models/basic_dataloader.py). You can start from there and modify it to suit your needs.

Hint: Resizing the inputs to 256x256 may not be the optimal solution.

**Comment by Flrotm** [comment]
Oh, did not know it was supposed to be a placeholder. Thank you anyway!
